### ISSUE TITLE
Messenger for Metarhia

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Console#2]
As a part of Console we need a simple messenger with function: personal messages, group conversation, file transfer (upload to server and download, not peer to peer), history (stored on device an on server), search, TLS encrypted transport. No registration, all user accounts are defined in database and can be changes just manually. @aqrln will prepare tasks and create server interface. Main platforms: Android, iOS, archaic Web. In the next step we may implement apps for Linux, Mac, Win.

Is it realistic to do that in 1 week?

**Comment by aqrln** [comment]
### Server

Implementation of the server is realistic in one week, but with some limitations. Actually, a huge part of it is already implemented as a JSTP demo, and it took about two days most which had been spent on improving JSTP for specific tasks, implementation of business logic took only a few hours. Now that JSTP is almost ready, it must not take long to code a messenger.

Here's the list of what is left unimplemented in JSTP and what is my main priority till the end of this week:
- JSTP over TLS and WebSocket (work in progress, almost done)
- Passing network errors to callbacks instead of never calling them if, for example, connection was lost
- Real authentication during handshake

Actually, granted that authentication can be implemented as RPC calls and underlying networking facilities are transparent and invisible to applied code, it is already possible to implement a messenger without file transfer feature.

What about files, we must design an extension to the JSTP protocol which will allow streaming of binary data. There's a concept of `stream` packets in the JSTP specification, and we had some ideas, but this should be discussed today, I think.

Right now we can send base64-encoded data over JSTP which is okay for small files but unacceptable for really big ones, so binary streaming is essential.

### Mobile applications

We have a simple single-channel messenger implemented for iOS and Android that used to operate via WebSocket protocol and a newer multi-channel one that uses JSTP. @Gagnant, @GYFK, @lidaamber and @lundibundi, how reusable is that code and how long will it take to implement the client-side of the real messenger?

### Web client

That should be quite easy to do as soon as JSTP over WebSocket is ready and ported from proper JavaScript to browser dialect of this language, which is my main task at the moment. Thus @sun1x will be able to start working on the client on Friday or Saturday. In order to focus on features and not waste time on design, you can use the gorgeous [Material-UI](http://www.material-ui.com) React components library.

### Desktop applications

As for me, desktop applications are even more important than the web version, but as a transitional step, we can use the web client with something like Electron or just make it a Chrome desktop application (we've seen a presentation about them at OdessaJS), it is better than nothing. Then we could implement it using Qt or Gtk (native for Linux and cross-platform at the same time) and, optionally, Cocoa for Mac.

### CLI client

Will inevitably be implemented as a testing utility, so it will be possible to fire up a terminal window and start chatting as soon as the server is ready.

**Comment by lundibundi** [comment]
@tshemsedinov I think this can be closed now, wdyt?
